# Generated by Django 5.2.7 on 2025-12-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_internshipprogram_location_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'На рассмотрении'), ('shortlisted', 'В шорт-листе'), ('rejected', 'Отклонена'), ('accepted', 'Принята')], default='applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('part_time', 'Неполный день'), ('full_time', 'Полный день'), ('internship', 'Стажировка'), ('volunteer', 'Волонтёрство')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('employer', 'Работодатель')], default='student', max_length=20),
        ),
    ]
